emit:
  - "@typespec/json-schema"
  - "@typespec/openapi3"
options:
  "@typespec/json-schema":
    emitAllModels: true
    emitAllRefs: true
  "@typespec/openapi3":
    output-file: "api-spec.yaml"
    emitAllModels: true
